services:

  db:
    ports:
      - 5432:5432
    container_name:  postgresql_container
    image: postgres
    environment:
      - POSTGRES_DB=loyaiDB
      - POSTGRES_PASSWORD=987654321
      - POSTGRES_USER=postgres
    restart: always

  backend:
    build: .
    container_name: loyai_service_container
    ports:
      - 8080:8080
    env_file:
      - variables.env

    depends_on:
      - db
    restart: always



